import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Auth | UTCC Educator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="-mt-24 -mb-28 h-screen">{children}</div>;
}
