import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Auth | UTCC Educator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="max-h-full">{children}</div>
    </div>
  );
}
