import type { Metadata } from "next";
import Footer from "@/components/footer";
import { NextLoaderComponent } from "@/components/core/next-loader";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "IPad, Laptop | UTCC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {process.env.NODE_ENV === "production" && (
          <Script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client="
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
        )}
      </head>
      <body className="">
        <Toaster />
        <NextLoaderComponent />
        {children}

        <Footer />
      </body>
    </html>
  );
}
