import { QAComponent } from "@/components/q_a-component";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Q&A | UTCC Educator",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-between p-2 lg:p-20">
      <QAComponent />
    </main>
  );
}
